### ISSUE TITLE
scalacheck law violation: voided only changes the result

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats-parse#263]
```
==> X cats.parse.ParserTest.voided only changes the result  0.213s munit.ComparisonFailException: /home/runner/work/cats-parse/cats-parse/core/shared/src/test/scala/cats/parse/ParserTest.scala:756
377
755:
378
756:      assertEquals(r2, r1.map { case (off, _) => (off, ()) })
379
757:      assertEquals(r2, r3)
380
values are not the same
381
=> Obtained
382
Left(
383
  value = Error(
384
    failedAtOffset = 0,
385
    expected = NonEmptyList(
386
      head = WithContext(
387
        contextStr = "\u9fe9\u0889ᕙ륱",
388
        expect = InRange(
389
          offset = 0,
390
          lower = '켥',
391
          upper = '켥'
392
        )
393
      ),
394
      tail = Nil
395
    )
396
  )
397
)
398
=> Diff (- obtained, + expected)
399
     expected = NonEmptyList(
400
-      head = WithContext(
401
-        contextStr = "\u9fe9\u0889ᕙ륱",
402
-        expect = InRange(
403
-          offset = 0,
404
-          lower = '켥',
405
-          upper = '켥'
406
-        )
407
+      head = Fail(
408
+        offset = 0
409
       ),
410
-      tail = Nil
411
+      tail = List(
412
+        WithContext(
413
+          contextStr = "\u9fe9\u0889ᕙ륱",
414
+          expect = InRange(
415
+            offset = 0,
416
+            lower = '켥',
417
+            upper = '켥'
418
+          )
419
+        )
420
+      )
421
     )
422

423
Failing seed: Ova1uT18mkE4uTX4RdgQza6z70fxyv6micl4hIZvywP=
424
You can reproduce this failure by adding the following override to your suite:
425

426
  override val scalaCheckInitialSeed = "Ova1uT18mkE4uTX4RdgQza6z70fxyv6micl4hIZvywP="
427

428
Falsified after 85 passed tests.
429
> ARG_0: GenT(Defer0(cats.parse.ParserGen$$$Lambda$11241/781764377@63a1bcdc))
430
> ARG_1: ""
431
> ARG_1_ORIGINAL: "嵧꽰톤"
432
    at munit.ComparisonFailException.withMessage(ComparisonFailException.scala:30)
433
    at munit.ComparisonFailException.withMessage(ComparisonFailException.scala:17)
434
    at munit.ScalaCheckSuite.propToTry(ScalaCheckSuite.scala:91)
435
    at munit.ScalaCheckSuite.$anonfun$scalaCheckPropTransform$3(ScalaCheckSuite.scala:46)
436
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:439)
437
    at munit.Suite$$anon$1.execute(Suite.scala:26)
438
    at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:393)
439
    at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
440
    at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
441
    at scala.concurrent.impl.Promise$DefaultPromise.transform(Promise.scala:128)
442
    at munit.internal.FutureCompat$ExtensionFuture.transformCompat(FutureCompat.scala:16)
443
    at munit.ScalaCheckSuite.$anonfun$scalaCheckPropTransform$2(ScalaCheckSuite.scala:48)
444
    at munit.GenericTest.$anonfun$withBodyMap$1(GenericTest.scala:33)
445
    at munit.MUnitRunner.$anonfun$runTestBody$1(MUnitRunner.scala:296)
```

**Comment by johnynek** [comment]
```
values are not the same
397
=> Obtained
398
Left(
399
  value = Error(
400
    failedAtOffset = 0,
401
    expected = NonEmptyList(
402
      head = WithContext(
403
        contextStr = "戼ῼ\uf7dfȡ왵ຽ閆䢛兗\ue22f嫙슢ﯭ鼼",
404
        expect = OneOfStr(
405
          offset = 0,
406
          strs = List(
407
            "\u2b45ꔣ\ue00d\u2f23"
408
          )
409
        )
410
      ),
411
      tail = Nil
412
    )
413
  )
414
)
415
=> Diff (- obtained, + expected)
416
     expected = NonEmptyList(
417
-      head = WithContext(
418
-        contextStr = "戼ῼ\uf7dfȡ왵ຽ閆䢛兗\ue22f嫙슢ﯭ鼼",
419
-        expect = OneOfStr(
420
-          offset = 0,
421
-          strs = List(
422
-            "\u2b45ꔣ\ue00d\u2f23"
423
+      head = Fail(
424
+        offset = 0
425
+      ),
426
+      tail = List(
427
+        WithContext(
428
+          contextStr = "戼ῼ\uf7dfȡ왵ຽ閆䢛兗\ue22f嫙슢ﯭ鼼",
429
+          expect = OneOfStr(
430
+            offset = 0,
431
+            strs = List(
432
+              "\u2b45ꔣ\ue00d\u2f23"
433
+            )
434
           )
435
         )
436
-      ),
437
-      tail = Nil
438
+      )
439
     )
440

441
Failing seed: bUQvEfxFZ73bxtVjauK8tJDrEKOFbxUfk6WrGiy3bkH=
442
You can reproduce this failure by adding the following override to your suite:
443

444
  override val scalaCheckInitialSeed = "bUQvEfxFZ73bxtVjauK8tJDrEKOFbxUfk6WrGiy3bkH="
445

446
Falsified after 295 passed tests.
447
> ARG_0: GenT(OneOf0(List(Map(SoftProd(Fail(),Pure((1640032260,-428115463))),org.scalacheck.GenArities$$Lambda$10903/322047275@6fe3267a), Map0(WithContextP0(戼ῼȡ왵ຽ閆䢛兗嫙슢ﯭ鼼,Str(⭅ꔣ⼣)),org.scalacheck.GenArities$$Lambda$10903/322047275@2ee8aa8a))))
448
> ARG_1: ""
449
> ARG_1_ORIGINAL: "雷㪆態䭐缉㋕"
```
